services:
  api:
    container_name: pageswarm-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - localstack

  localstack:
    container_name: localstack
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack-data:/var/lib/localstack
